// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TsLaser.Crm.Api.Infrastructure.Persistence;

#nullable disable

namespace TsLaser.Crm.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260404073342_BookingModerationFlow")]
    partial class BookingModerationFlow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("TsLaser.Crm.Api.Domain.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("birth_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferralCustom")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("referral_custom");

                    b.Property<int?>("ReferralPartnerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("referral_partner_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("active");

                    b.Property<string>("StoppedReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("stopped_reason");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_clients_name");

                    b.HasIndex("Phone")
                        .HasDatabaseName("ix_clients_phone");

                    b.HasIndex("ReferralPartnerId");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("TsLaser.Crm.Api.Domain.Entities.IntakeSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ApprovedClientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("approved_client_id");

                    b.Property<int?>("ApprovedTattooId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("approved_tattoo_id");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("birth_date");

                    b.Property<int?>("ClientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("client_id");

                    b.Property<string>("CorrectionsInfo")
                        .HasColumnType("TEXT")
                        .HasColumnName("corrections_info");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DesiredResult")
                        .HasColumnType("TEXT")
                        .HasColumnName("desired_result");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsNewClient")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_new_client");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.Property<string>("PreviousRemovalInfo")
                        .HasColumnType("TEXT")
                        .HasColumnName("previous_removal_info");

                    b.Property<string>("PreviousRemovalWhere")
                        .HasColumnType("TEXT")
                        .HasColumnName("previous_removal_where");

                    b.Property<string>("RawPayload")
                        .HasColumnType("TEXT")
                        .HasColumnName("raw_payload");

                    b.Property<string>("ReferralSource")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("referral_source");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("rejection_reason");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("reviewed_at");

                    b.Property<string>("ReviewedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("reviewed_by");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("landing")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<string>("TattooAge")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("tattoo_age");

                    b.Property<int?>("TattooId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tattoo_id");

                    b.Property<string>("TattooType")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("tattoo_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedClientId")
                        .HasDatabaseName("ix_intake_submissions_approved_client_id");

                    b.HasIndex("ApprovedTattooId")
                        .HasDatabaseName("ix_intake_submissions_approved_tattoo_id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_intake_submissions_client_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_intake_submissions_created_at");

                    b.HasIndex("Phone")
                        .HasDatabaseName("ix_intake_submissions_phone");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_intake_submissions_status");

                    b.HasIndex("TattooId")
                        .HasDatabaseName("ix_intake_submissions_tattoo_id");

                    b.ToTable("intake_submissions", (string)null);
                });

            modelBuilder.Entity("TsLaser.Crm.Api.Domain.Entities.LaserSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BreakPeriod")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("break_period");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("client_id");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Density")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("density");

                    b.Property<string>("Diameter")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("diameter");

                    b.Property<int?>("FlashesCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("flashes_count");

                    b.Property<string>("Hertz")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("hertz");

                    b.Property<DateOnly?>("SessionDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_date");

                    b.Property<int?>("SessionNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("session_number");

                    b.Property<string>("SubSession")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("sub_session");

                    b.Property<int?>("TattooId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tattoo_id");

                    b.Property<string>("TattooName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("tattoo_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("Wavelength")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("wavelength");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_laser_sessions_client_id");

                    b.HasIndex("TattooId")
                        .HasDatabaseName("ix_laser_sessions_tattoo_id");

                    b.ToTable("laser_sessions", (string)null);
                });

            modelBuilder.Entity("TsLaser.Crm.Api.Domain.Entities.Partner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<string>("Contacts")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Terms")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_partners_name");

                    b.ToTable("partners", (string)null);
                });

            modelBuilder.Entity("TsLaser.Crm.Api.Domain.Entities.Tattoo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("client_id");

                    b.Property<string>("CorrectionsCount")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("corrections_count");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DesiredResult")
                        .HasColumnType("TEXT")
                        .HasColumnName("desired_result");

                    b.Property<DateOnly?>("LastLaserDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_laser_date");

                    b.Property<DateOnly?>("LastPigmentDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_pigment_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("NoLaserBefore")
                        .HasColumnType("INTEGER")
                        .HasColumnName("no_laser_before");

                    b.Property<string>("PreviousRemovalPlace")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("previous_removal_place");

                    b.Property<string>("RemovalZone")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("removal_zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_tattoos_client_id");

                    b.ToTable("tattoos", (string)null);
                });

            modelBuilder.Entity("TsLaser.Crm.Api.Domain.Entities.Client", b =>
                {
                    b.HasOne("TsLaser.Crm.Api.Domain.Entities.Partner", "ReferralPartner")
                        .WithMany("ReferredClients")
                        .HasForeignKey("ReferralPartnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ReferralPartner");
                });

            modelBuilder.Entity("TsLaser.Crm.Api.Domain.Entities.IntakeSubmission", b =>
                {
                    b.HasOne("TsLaser.Crm.Api.Domain.Entities.Client", "Client")
                        .WithMany("IntakeSubmissions")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TsLaser.Crm.Api.Domain.Entities.Tattoo", "Tattoo")
                        .WithMany("IntakeSubmissions")
                        .HasForeignKey("TattooId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Client");

                    b.Navigation("Tattoo");
                });

            modelBuilder.Entity("TsLaser.Crm.Api.Domain.Entities.LaserSession", b =>
                {
                    b.HasOne("TsLaser.Crm.Api.Domain.Entities.Client", "Client")
                        .WithMany("Sessions")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TsLaser.Crm.Api.Domain.Entities.Tattoo", "Tattoo")
                        .WithMany("Sessions")
                        .HasForeignKey("TattooId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Client");

                    b.Navigation("Tattoo");
                });

            modelBuilder.Entity("TsLaser.Crm.Api.Domain.Entities.Tattoo", b =>
                {
                    b.HasOne("TsLaser.Crm.Api.Domain.Entities.Client", "Client")
                        .WithMany("Tattoos")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("TsLaser.Crm.Api.Domain.Entities.Client", b =>
                {
                    b.Navigation("IntakeSubmissions");

                    b.Navigation("Sessions");

                    b.Navigation("Tattoos");
                });

            modelBuilder.Entity("TsLaser.Crm.Api.Domain.Entities.Partner", b =>
                {
                    b.Navigation("ReferredClients");
                });

            modelBuilder.Entity("TsLaser.Crm.Api.Domain.Entities.Tattoo", b =>
                {
                    b.Navigation("IntakeSubmissions");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
